workdir: "."
# Download parameters for fastq-dump (leave empty unless testing)
dlparams: ""
sample_file_list: "sample_list.tsv"
datadir: "data/raw"
mem_per_cpu: 6
## data for filtering
fungi_info: "https://mycocosm.jgi.doe.gov/fungi/fungi.info.html"
host_fna: ""
host_gff: ""
# partition reads into taxonomic bins
taxmap:
  Bacteria: 2
  Archaea: 2157
  Eukaryota: 2759
## mapping
host_aligner: "star"
bowtie2_params: "--very-sensitive"
# star_limitGenomeGenerateRAM sets the maximum allowed RAM usage (in GB)
star_limitGenomeGenerateRAM: 128
# star_extra_build_params sets the extra parameters for star index build
star_extra_build_params: "--genomeChrBinNbits 15 --genomeSAsparseD 3 --genomeSAindexNbases 14 --sjdbGTFtagExonParentTranscript Parent --sjdbOverhang 100"
# star_extra_params sets the extra parameters for star alignment
# if STAR aligner fails to map reads to host, consider lowering the values below
# in order to increase sensitivity of the aligner. WARNING: Note that this may
# increase the number of false positive host reads meaning that fungal reads
# may end up in the 'host' bin
star_extra_params: "--outFilterScoreMinOverLread 0.66 --outFilterMatchNminOverLread 0.66 --seedSearchStartLmax 50"
# feature counts
fc_params: "-p -t mRNA -g ID -Q 10"
## assembly
# Choose between 'megahit', 'trinity', 'transabyss'
assembler: trinity
transabyss_kmers: [21, 25, 29, 31, 65, 75, 85, 95]
co_assembly: True
single_assembly: False
min_contig_len: 200
insilico_norm_max_cov: 30
insilico_norm_mem: "100G"
## Filtering is performed by first mapping reads to fungi transcriptomes, then taking mappead reads and mapping them to a host genome.
## Reads that come out as unmapped in the second step are considered as fungal reads.
filter_reads: True
# Choose between 'concordant', 'both_mapped' or 'one_mapped'
paired_strategy: "one_mapped"
# trimmomatic
trimmomatic_home: ""
qc_trim_settings: "LEADING:25 TRAILING:25 SLIDINGWINDOW:4:15 HEADCROP:2 MINLEN:50"
# diamond
diamond_fasta_url: "https://zenodo.org/record/3737678/files/fasta.gz?download=1"
diamond_nodes_url: "https://zenodo.org/record/3737678/files/nodes.dmp.gz?download=1"
diamond_taxonmap_url: "https://zenodo.org/record/3737678/files/taxonmap.gz?download=1"
# dbCAN (Suggested thresholds for fungi, see: http://csbl.bmb.uga.edu/dbCAN/download/readme.txt)
dbCAN_eval: 0.00000000000000001
dbCAN_cov: 0.45
tax_rank: kingdom
tax_name: Fungi
