workdir: "."
# Download parameters for fastq-dump (leave empty unless testing)
dlparams: ""
sample_file_list: "sample_list.tsv"
datadir: "data/raw"
mem_per_cpu: 6
## data for filtering
fungi_transcript_url: "https://zenodo.org/record/3550762/files/fungi_transcripts.fasta.gz?download=1"
spruce_transcript_url: "https://zenodo.org/record/3550762/files/spruce.fna.gz?download=1"
## mapping
bowtie2_params: "--very-sensitive"
fc_params: "-B -p -t CDS -g gene_id -Q 10"
## assembly
# Choose between 'megahit', 'trinity', 'transabyss'
assembler: transabyss
transabyss_kmers: [21, 25, 29, 31, 65, 75, 85, 95]
co-assembly: True
single-assembly: False
min_contig_len: 200
## filtering
# Choose between 'concordant', 'both-mapped' or 'one-mapped'
paired_strategy: "both-mapped"
# Choose between 'unfiltered', 'bowtie2', 'taxmapper' or 'filtered' (using a combination)
read_source: "filtered"
# trimmomatic
trimmomatic_home: ""
qc_trim_settings: "LEADING:25 TRAILING:25 SLIDINGWINDOW:4:15 HEADCROP:2 MINLEN:50"
# diamond
diamond_fasta_url: "https://zenodo.org/record/3737678/files/fasta.gz?download=1"
diamond_nodes_url: "https://zenodo.org/record/3737678/files/nodes.dmp.gz?download=1"
diamond_taxonmap_url: "https://zenodo.org/record/3737678/files/taxonmap.gz?download=1"
# dbCAN (Suggested thresholds for fungi, see: http://csbl.bmb.uga.edu/dbCAN/download/readme.txt)
dbCAN_eval: 0.00000000000000001
dbCAN_cov: 0.45
tax_rank: kingdom
tax_name: Fungi
