name: fungal-trans
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - snakemake-minimal
  - biopython
  - pandas
  - lxml
  - pycurl
  - tqdm
  - multiqc
  - bowtie2
  - samtools
  - ete3
  - fastuniq
  - seqtk

  # utilities
  - wget
  - tbb
  - mamba
