name: fungal-trans
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - snakemake-minimal>=8.0.0
  - biopython
  - pandas==1.5.1
  - lxml
  - pycurl
  - tqdm
  - multiqc
  - bowtie2
  - samtools=1.15
  - ete3
  - fastuniq
  - seqtk
  - seqkit

  # utilities
  - wget
  - tbb
  - mamba
