name: fungal-trans
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - snakemake-minimal=6.2.1
  - biopython=1.78
  - pandas=1.3.4
  - multiqc=1.11
  - bowtie2=2.4.4
  - samtools=1.14
  - ete3=3.1.2
  - fastuniq=1.1
  - seqtk=1.3

  # utilities
  - wget
  - tbb
  - mamba
