name: default
channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- python *
- mamba *
- snakemake >=9
- biopython *
- tqdm *
- pandas *
- polars *
- pyarrow *
- lxml *
- pycurl *
- pip *
- seqtk *
- seqkit *
- multiqc *
- ete3 *
- snakemake-executor-plugin-slurm *
- pigz *
- nextflow >=25.4.7,<26
