[project]
name = "fungal-trans"
version = "0.1.0"
description = "A Snakemake workflow for fungal metatranscriptomics"
authors = ["johnne <john.sundh@scilifelab.se>"]
channels = ["conda-forge", "bioconda", "main", "r", "msys2"]
platforms = ["linux-64"]

[system-requirements]
linux="5.3.18"

[tasks]
init = "conda config --set channel_priority strict"

[dependencies]
python = "*"
mamba = "*"
snakemake = ">=9"
biopython = "*"
tqdm = "*"
pandas = "*"
lxml = "*"
pycurl = "*"
pip = "*"
seqtk = "*"
seqkit = "*"
multiqc = "*"
ete3 = "*"
snakemake-executor-plugin-slurm = "*"
pigz = "*"