# This is the configuration profile for the Dardel HPC system Read more about
# the available partitions at https://support.pdc.kth.se/doc/support/

# There are 128 physical cores per node on Dardel, with 2 threads per core, and
# each node has 256 GB of memory of which a certain amount is reserved for the
# system, depending on the type of node.

# Thin nodes: 227.328 GB available for jobs. This means that there is 227328 /
# 256 = 888 MB of memory available per thread.

# Large nodes: 456.704 GB available for jobs. This means that there is 456704 / 256
# = 1784 MB of memory available per thread.

# Huge nodes: 915.456 GB available for jobs. This means that there is 915456 / 128
# = 3576 MB of memory available per thread.

# Giant nodes: 1.832.960 GB available for jobs. This means that there is 1832960
# / 128 = 7160 MB of memory available per thread.

# the resource definitions below specify the default used by all rules unless overridden by 
# the set-resources section
default-resources: 
  slurm_account: <your-slurm-account>
  slurm_partition: shared
  runtime: 120
  tasks: f"{threads}"
  cpus_per_task: 1

# The set-resources section specifies the resources to use for specific rules, this overrides
# the default resources
set-resources:
  # db.smk
  mmseqs_extract_fungalDB:
    runtime: 120
    mem_mb: 35200
  mmseqs_convert2fasta_fungalDB:
    runtime: 60
    mem_mb: 18648
  mmseqs_createseqdb:
    runtime: 30
    mem_mb: 3552
  mmseqs_create_taxidmap:
    mem_mb: 97680
    runtime: 60
  mmseqs_createtaxdb:
    runtime: 60
    mem_mb: 3552
  mmseqs_secondpass_taxonomy_co:
    runtime: 240
    mem_mb: 35520
  mmseqs_secondpass_taxonomy:
    runtime: 240
    mem_mb: 35520
  # preprocess.smk
  trimmomatic:
    runtime: 60
  sortmerna:
    runtime: 240
    mem_mb: 128000
  # filter.smk
  strobealign_build_fungi:
    runtime: 240
    mem_mb: 64000
  strobealign_map_fungi:
    runtime: 720
    mem_mb: 64000
  bowtie_build_fungi:
    runtime: 720
    mem_mb: 915456
    slurm_partition: memory
  bowtie_map_fungi:
    runtime: 720
    mem_mb: 227328
  star_build_host:
    runtime: 1440
  star_map_host:
    slurm_partition: shared
    mem_mb: 96000
  host_reads:
    mem_mb: 40000
    runtime: 360
  fastq_stats:
    runtime: 30
  # kraken.smk
  preload_kraken_db:
    slurm_partition: main
    runtime: 10
    mem_mb: 440000
  run_kraken:
    slurm_partition: main
    runtime: 30
  unload_kraken_db:
    slurm_partition: main
    runtime: 10
  # annotate.smk
  transdecoder_longorfs_co:
    runtime: 60
    mem_mb: 888
  transdecoder_longorfs:
    runtime: 60
    mem_mb: 888
  mmseqs_createquerydb_longorfs_co:
    runtime: 60
    mem_mb: 3552
  mmseqs_createquerydb_longorfs:
    runtime: 60
    mem_mb: 3552
  mmseqs_firstpass_taxonomy_co:
    runtime: 60
    mem_mb: 3552
  mmseqs_firstpass_taxonomy:
    runtime: 60
    mem_mb: 3552
  transdecoder_predict_co:
    runtime: 60
    tasks: 1
    mem_mb: 888
  mmseqs_createquerydb_co:
    runtime: 60
    mem_mb: 3552
    tasks: 1
  mmseqs_addtaxonomy_co:
    runtime: 60
    mem_mb: 3552
    tasks: 1
  mmseqs_createtsv_first_co:
    runtime: 30
    mem_mb: 888
    tasks: 1
  mmseqs_taxonomy_co:
    runtime: 1440
    tasks: 20
    mem_mb: 88800
  featurecount:
    runtime: 60
  emapper_search_co:
    runtime: 1440
  contigtax_search_co:
    runtime: 2880
    mem_mb: 128000
  assign_taxonomy_co:
    mem_mb: 64000
  emapper_annotate_hits_co:
    mem_mb: 64000
# assembly.smk
  trinity_normalize:
    runtime: 1440
    mem_mb: 128000
  trinity_co:
    runtime: 600
    mem_mb: 8880
  megahit_co:
    mem_mb: 17000
    runtime: 600
  transabyss_co:
    mem_mb: 17000
    runtime: 1440
  transabyss_merge_co:
    mem_mb: 17000
    runtime: 1440
  trinity:
    runtime: 600
    mem_mb: 5328
    tasks: 6
# map.smk
  bowtie_co:
    runtime: 240
    mem_mb: 32000
  bowtie:
    runtime: 60
  bowtie_build:
    runtime: 60
    mem_mb: 888
  samtools_sort:
    runtime: 240
# paired_strategy.smk
  fungi_one_mapped:
    runtime: 180
  fungi_both_mapped:
    runtime: 180
    mem_mb: 6000

set-threads:
  # assembly.smk
  megahit_co: 20
  trinity_normalize: 6
  transabyss_co: 20
  transabyss_merge_co: 20
  bowtie_build_fungi: 100
  bowtie_map_fungi: 80
  sortmerna: 128
  host_reads: 10
  star_map_host: 96
  run_kraken: 20
  trinity: 6
  trinity_co: 6

# Snakemake command line options
keep-going: True
printshellcmds: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 200
latency-wait: 5
executor: slurm
software-deployment-method: "apptainer"
use-conda: False
apptainer-args: "--bind $PDC_TMP,$PWD,/sw/data --env TMPDIR=$PDC_TMP"