$schema: "http://json-schema.org/draft-06/schema#"
description: Configuration schema
properties:
  ## PATHS ##
  workdir:
    type: string
    default: .
    description: Work directory for workflow
  sample_file_list:
    type: string
    description: Sample information file
    default: "sample_list.tsv"
  datadir:
    type: string
    description: Directory with raw sequence files
    default: "data/raw"
  read_length:
    type: integer
    description: Read length of samples
    default: 150
  ## SRA DOWNLOAD ##
  dlparams:
    type: string
    description: Parameters to supply to sra-tools for development purposes
    default: ""
  ## PREPROCESSING ##
  trimmomatic_home:
    type: string
    description: Trimmomatic home path (will be detected automatically)
    default: ""
  qc_trim_settings:
    type: string
    description: Trimmomatic trim settings
    default: "LEADING:25 TRAILING:25 SLIDINGWINDOW:4:15 HEADCROP:2 MINLEN:50"
  cutadapt_R1:
    type: string
    description: Cutadapt R1 adapter
    default: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  cutadapt_R2:
    type: string
    description: Cutadapt R2 adapter
    default: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  cutadapt_error_rate:
    type: number
    description: Cutadapt maximum error rate
    default: 0.2
  cutadapt_extra_settings:
    type: string
    description: Additional flags for cutadapt
    default: ""
  ## FILTERING ##
  filter_reads:
    type: boolean
    description: Whether to filter reads
    default: true
  paired_strategy:
    type: string
    description: Strategy for handling read pairs. If 'both_mapped', both reads in a pair must map to fungi and neither to host. If 'one_mapped', only one read in a pair must map to fungi and pairs with at least one read mapping to host will be discarded.
    default: "one_mapped"
    enum: ["both_mapped","one_mapped"]
  fungi_info:
    type: string
    description: URL to fungi info page
    default: https://mycocosm.jgi.doe.gov/fungi/fungi.info.html
  jgi_user:
    type: string
    description: JGI username
    default: ""
  jgi_password:
    type: string
    description: JGI password
    default: ""
  host_fna:
    type: string
    description: Path to host fasta file
    default: ""
  host_gff:
    type: string
    description: Path to host GFF file
    default: ""
  # STAR parameters
  star_limitGenomeGenerateRAM:
    type: integer
    description: Maximum RAM to use for genome generation (in GB)
    default: 128
  star_extra_build_params:
    type: string
    description: Extra parameters for star index build
    default: "--genomeChrBinNbits 15 --genomeSAsparseD 3 --genomeSAindexNbases 14 --sjdbGTFtagExonParentTranscript Parent"
  star_extra_params:
    type: string
    description: Extra parameters for star alignment
    default: "--outFilterScoreMinOverLread 0.66 --outFilterMatchNminOverLread 0.66 --seedSearchStartLmax 50"
  
  ## ASSEMBLY ##
  co-assembly:
    type: boolean
    description: Whether to create co-assemblies
    default: true
  single-assembly:
    type: boolean
    description: Whether to create single-assemblies
    default: false
  assembler:
    type: string
    description: Assembler to use
    default: "trinity"
    enum: ["trinity", "megahit", "transabyss"]
  transabyss_kmers:
    type: array
    description: Kmer lengths to use for transabyss
    default: [21, 25, 29, 31, 65, 75, 85, 95]
    items:
      type: integer
  min_contig_len:
    type: integer
    description: Minimum contig length for megahit assembler
    default: 200
  insilico_norm_max_cov:
    type: integer
    description: Target max coverage for insilico normalization
    default: 30
  insilico_norm_mem:
    type: string
    description: Maximum memory to use for insilico normalization
    default: "100G"
  ## ANNOTATION ##
  mmseqs_db_dir:
    type: string
    description: Path to MMSeqs2 databases
    default: "/sw/data/MMseqs2_data/latest/rackham"
  transdecoder_homology_db:
    type: string
    description: Database for TransDecoder homology filtering
    default: "UniProtKB_Swiss-Prot"
  mmseqs_db:
    type: string
    description: Database for MMSeqs2 taxonomic assignment
    default: "NR"
  extra_genomes:
    type: string
    description: File listing additional genomes for taxonomic assignment
    default: "extra_JGI_genomes.tsv"
  emapper_db_dir:
    type: string
    description: Path to eggNOG database
    default: "/sw/data/eggnog/5.0/rackham"
  dbCAN_eval:
    type: number
    description: E-value to use for dbCAN parsing
    default: 0.00000000000000001
  dbCAN_cov:
    type: number
    description: Coverage threshold for dbCAN parsing
    default: 0.45
  tax_rank:
    type: string
    description: Taxonomic rank to summarize eggNOG annotations for
    default: "kingdom"
    enum: ["superkingdom","kingdom","phylum","class","order","family","genus","species"]
  tax_name:
    type: string
    description: Taxonomic name at which to summarize eggNOG annotations for
    default: "Fungi"
  ## READ ASSIGNMENT ##
  fc_params:
    type: string
    description: Parameters for featureCounts
    default: "-s 2 -p -B -t CDS -g gene_id -Q 10"
  ## READ PARTITIONING ##
  kraken_db:
    type: string
    description: Path to Kraken database
    default: "/sw/data/Kraken2_data/prebuilt/k2_pluspfp_20240112"
  taxmap:
    type: object
    description: Taxonomic mapping for partitioning
    properties:
      Bacteria:
        type: integer
        description: NCBI taxon ID for Bacteria
        default: 2
      Archaea:
        type: integer
        description: NCBI taxon ID for Archaea
        default: 2157
      Eukaryota:
        type: integer
        description: NCBI taxon ID for Eukaryota
        default: 2759