title: "Fungal metatranscriptomics preprocessing report"
subtitle: "Sample report for the preprocessing steps"
intro_text: ""
report_comment: "Preprocessing was done with Cutadapt (v.1.18) to remove adapters and Trimmomatic (v 0.38) for quality trimming"


sp:
    featurecounts:
        fn: '*.log'
        contents: 'Status'
extra_fn_clean_exts:
    - '.cut'
    - '.cut.trim'
    - '.bt.log'
    - '.bowtie.log'
    - '.bowtie2.log'
