title: "Fungal metatranscriptomics preprocessing report"
subtitle: "Sample report for the preprocessing steps"
intro_text: ""
report_comment: "Preprocessing was done with Cutadapt to remove adapters and Trimmomatic for quality trimming followed by rRNA removal with SortMeRNA"
show_analysis_paths: False

sp:
    featurecounts:
        fn: '*.log'
        contents: 'Status'
extra_fn_clean_exts:
    - '.cut'
    - '.cut.trim'
    - '.bt.log'
    - '.bowtie.log'
    - '.bowtie2.log'
    - type: truncate
      pattern: '_R2'
      module: 'sortmerna'
