title: "Fungal metatranscriptomics preprocessing report"
subtitle: "Sample report for read filtering"
intro_text: ""

extra_fn_clean_exts:
    - '.cut'
    - '.cut.trim'
    - '.bt.log'
    - '.bowtie.log'
