name: Testing

on:
  workflow_dispatch:
    branches:
      - main
      - filtering
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - main
env:
  TMPDIR: /tmp

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo + LFS
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS files
        run: git lfs pull
      - name: Set upp conda
        uses: s-weigand/setup-conda@v1
      - name: Install the conda environment
        run: conda env update -n base -f environment.yml
      - name: Dry-run
        run: |
          snakemake --use-conda -rpk -j 4 -n